# load our own booting sequence
require File.expand_path('../../config/boboot', __FILE__)
Boboot.require_boot!

require 'rake'
require 'rake/task'
require 'thomas'

config = Thomas.config
bconfig = config['baseruby']
docker_config = bconfig['docker']

docker_opts = Thomas::Helper.symbolize_keys(docker_config)
Thomas.include_docker_tasks(docker_opts)
