require File.expand_path('../../config/boboot', __FILE__)
Boboot.require_boot!

require 'rake'
require 'rake/task'
require 'thomas'

config = Thomas.config
biconfig = config['baseimage']
docker_config = biconfig['docker']

docker_opts = Thomas::Helper.symbolize_keys(docker_config)
Thomas.include_docker_tasks(docker_opts)
